version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: social-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_platform
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - social_net

  redis:
    image: redis:7.0
    container_name: social-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - social_net

  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: social-nacos
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - social_net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: social-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - social_net

  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: social-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - social_net

networks:
  social_net:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  elasticsearch_data:
