server:
  port: 8082

spring:
  application:
    name: message-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/social_message?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      database: 1

security:
  ignore-urls:
    - /doc.html
    - /webjars/**
    - /swagger-resources/**
    - /v3/api-docs/**

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.socialplatform.message.model
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: true
      logic-not-delete-value: false

logging:
  level:
    com.socialplatform: debug
