server:
  port: 8081

spring:
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/social_auth?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

jwt:
  secret: your-secret-key-here-please-change-in-production
  expiration: 86400000  # 24小时
  header: Authorization
  token-prefix: "Bearer "

security:
  ignore-urls:
    - /auth/login
    - /auth/register
    - /auth/captcha
    - /doc.html
    - /webjars/**
    - /swagger-resources/**
    - /v3/api-docs/**

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.socialplatform.auth.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.socialplatform: debug
